/**
 * Converter - FingerprintManager
 * File fingerprint generation and verification for tracking config changes
 */

import { promises as fs } from 'fs';
import * as crypto from 'crypto';
import * as path from 'path';

// ============================================
// Type definitions
// ============================================

/**
 * File fingerprint
 */
export interface FileFingerprint {
  /** File path (relative) */
  path: string;
  /** Content hash (SHA-256) */
  hash: string;
  /** Last generated time */
  lastGenerated: string;
  /** Generator version */
  generator: string;
  /** File size */
  size: number;
}

/**
 * Fingerprint verification result
 */
export interface FingerprintVerification {
  /** Verification status */
  status: 'new' | 'modified' | 'unchanged';
  /** Whether file is modified */
  modified: boolean;
  /** Last generated time */
  lastGenerated?: string;
  /** Generator version */
  generatedBy?: string;
}

/**
 * Fingerprint storage
 */
interface FingerprintStore {
  version: string;
  fingerprints: Record<string, FileFingerprint>;
  updatedAt: string;
}

// ============================================
// Constants
// ============================================

const STORE_FILENAME = '.unify-ai/fingerprints.json';
const STORE_VERSION = '1.0.0';

// ============================================
// FingerprintManager class
// ============================================

/**
 * Fingerprint manager
 * Manages file fingerprints for change detection
 */
export class FingerprintManager {
  private fingerprints: Map<string, FileFingerprint> = new Map();
  private storePath: string;
  private dirty: boolean = false;

  /**
   * Create a new FingerprintManager
   * @param projectRoot Project root directory
   */
  constructor(projectRoot: string = process.cwd()) {
    this.storePath = path.join(projectRoot, STORE_FILENAME);
  }

  /**
   * Generate a fingerprint for a file
   * @param filePath File path
   * @param content File content
   * @returns File fingerprint
   */
  generate(filePath: string, content: unknown): FileFingerprint {
    const normalizedPath = this.normalizePath(filePath);
    const hash = this.computeHash(content);
    const serialized = typeof content === 'string' ? content : JSON.stringify(content);

    return {
      path: normalizedPath,
      hash,
      lastGenerated: new Date().toISOString(),
      generator: STORE_VERSION,
      size: Buffer.byteLength(serialized, 'utf-8'),
    };
  }

  /**
   * Update fingerprint for a file
   * @param filePath File path
   * @param content File content
   * @param isGenerated Whether the file was generated by the system
   */
  update(filePath: string, content: unknown, isGenerated: boolean = false): void {
    const fingerprint = this.generate(filePath, content);
    if (isGenerated) {
      fingerprint.generator = STORE_VERSION;
    }
    this.fingerprints.set(this.normalizePath(filePath), fingerprint);
    this.dirty = true;
  }

  /**
   * Verify a file against its stored fingerprint
   * @param filePath File path
   * @param content File content
   * @returns Verification result
   */
  verify(filePath: string, content: unknown): FingerprintVerification {
    const normalizedPath = this.normalizePath(filePath);
    const stored = this.fingerprints.get(normalizedPath);

    if (!stored) {
      return {
        status: 'new',
        modified: true,
      };
    }

    const currentHash = this.computeHash(content);
    const modified = currentHash !== stored.hash;

    return {
      status: modified ? 'modified' : 'unchanged',
      modified,
      lastGenerated: stored.lastGenerated,
      generatedBy: stored.generator,
    };
  }

  /**
   * Get fingerprint for a file
   * @param filePath File path
   * @returns Fingerprint or undefined if not found
   */
  get(filePath: string): FileFingerprint | undefined {
    return this.fingerprints.get(this.normalizePath(filePath));
  }

  /**
   * Get all fingerprints
   * @returns Map of all fingerprints
   */
  getAll(): Map<string, FileFingerprint> {
    return new Map(this.fingerprints);
  }

  /**
   * Check if a file has been modified since last fingerprint
   * @param filePath File path
   * @returns True if modified
   */
  isModified(filePath: string): boolean {
    const normalizedPath = this.normalizePath(filePath);
    const stored = this.fingerprints.get(normalizedPath);
    return !stored;
  }

  /**
   * Remove fingerprint for a file
   * @param filePath File path
   */
  remove(filePath: string): void {
    const normalizedPath = this.normalizePath(filePath);
    if (this.fingerprints.delete(normalizedPath)) {
      this.dirty = true;
    }
  }

  /**
   * Clear all fingerprints
   */
  clear(): void {
    this.fingerprints.clear();
    this.dirty = true;
  }

  /**
   * Save fingerprints to disk
   */
  async save(): Promise<void> {
    if (!this.dirty) {
      return;
    }

    const storeDir = path.dirname(this.storePath);

    // Ensure directory exists
    try {
      await fs.mkdir(storeDir, { recursive: true });
    } catch {
      // Directory may already exist
    }

    const store: FingerprintStore = {
      version: STORE_VERSION,
      fingerprints: Object.fromEntries(this.fingerprints),
      updatedAt: new Date().toISOString(),
    };

    await fs.writeFile(this.storePath, JSON.stringify(store, null, 2), 'utf-8');
    this.dirty = false;
  }

  /**
   * Load fingerprints from disk
   */
  async load(): Promise<void> {
    try {
      const content = await fs.readFile(this.storePath, 'utf-8');
      const store: FingerprintStore = JSON.parse(content);

      if (store.version !== STORE_VERSION) {
        // Version mismatch, reset fingerprints
        this.fingerprints.clear();
        this.dirty = true;
        return;
      }

      this.fingerprints = new Map(Object.entries(store.fingerprints));
      this.dirty = false;
    } catch {
      // File doesn't exist or can't be read, start fresh
      this.fingerprints.clear();
      this.dirty = false;
    }
  }

  /**
   * Get the store file path
   * @returns Store file path
   */
  getStorePath(): string {
    return this.storePath;
  }

  /**
   * Check if there are unsaved changes
   * @returns True if there are unsaved changes
   */
  hasUnsavedChanges(): boolean {
    return this.dirty;
  }

  // ============================================
  // Private methods
  // ============================================

  /**
   * Compute hash for content
   */
  private computeHash(content: unknown): string {
    const normalized = typeof content === 'string'
      ? content
      : JSON.stringify(content, Object.keys(content as object).sort());
    return crypto
      .createHash('sha256')
      .update(normalized)
      .digest('hex');
  }

  /**
   * Normalize file path
   */
  private normalizePath(filePath: string): string {
    // Convert to forward slashes for consistency
    return filePath.replace(/\\/g, '/');
  }
}

// ============================================
// Export singleton factory
// ============================================

let defaultInstance: FingerprintManager | null = null;

/**
 * Get default FingerprintManager instance
 * @param projectRoot Project root directory
 * @returns FingerprintManager instance
 */
export function getFingerprintManager(projectRoot?: string): FingerprintManager {
  if (!defaultInstance) {
    defaultInstance = new FingerprintManager(projectRoot);
  }
  return defaultInstance;
}

/**
 * Create a new FingerprintManager instance
 * @param projectRoot Project root directory
 * @returns New FingerprintManager instance
 */
export function createFingerprintManager(projectRoot: string): FingerprintManager {
  return new FingerprintManager(projectRoot);
}
